services:
  hapi-server:
    image: hapiproject/hapi:v7.6.0
    mem_limit: "4G"
    restart: always
    depends_on:
      - hapi-postgres-db
    networks:
      - backend
    ports:
      - 127.0.0.1:8080:8080
    configs:
      - source: hapi
        target: /app/config/application.yaml
      - source: igs
        target: /app/igs
    volumes:
      - .luceneIndex:/opt/hapi_lucenefiles
    environment:
      JAVA_OPTS: -Xms512m -Xmx4g

  hapi-postgres-db:
    image: postgres:14
    restart: always
    networks:
      - backend
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - fhir_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hapi
      POSTGRES_USER: hapi
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
networks:
  backend:
    name: backend
volumes:
  fhir_postgres_data:
    driver: local

secrets:
  db_password:
    file: db_password.secret

configs:
  igs:
    file: ./igs
  hapi:
    file: ./application.yaml

